<?php

/**
 * BaseNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $user_id
 * @property bigint $sender_id
 * @property bigint $conference_id
 * @property string $body
 * @property sfGuardUser $Parent
 * @property sfGuardUser $Sender
 * @property Conference $Conference
 * 
 * @method bigint       getUserId()        Returns the current record's "user_id" value
 * @method bigint       getSenderId()      Returns the current record's "sender_id" value
 * @method bigint       getConferenceId()  Returns the current record's "conference_id" value
 * @method string       getBody()          Returns the current record's "body" value
 * @method sfGuardUser  getParent()        Returns the current record's "Parent" value
 * @method sfGuardUser  getSender()        Returns the current record's "Sender" value
 * @method Conference   getConference()    Returns the current record's "Conference" value
 * @method Notification setUserId()        Sets the current record's "user_id" value
 * @method Notification setSenderId()      Sets the current record's "sender_id" value
 * @method Notification setConferenceId()  Sets the current record's "conference_id" value
 * @method Notification setBody()          Sets the current record's "body" value
 * @method Notification setParent()        Sets the current record's "Parent" value
 * @method Notification setSender()        Sets the current record's "Sender" value
 * @method Notification setConference()    Sets the current record's "Conference" value
 * 
 * @package    platforms
 * @subpackage model
 * @author     Joerg Basedow <jbasedow@mindworks.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotification extends mwDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification');
        $this->hasColumn('user_id', 'bigint', null, array(
             'type' => 'bigint',
             'notnull' => true,
             ));
        $this->hasColumn('sender_id', 'bigint', null, array(
             'type' => 'bigint',
             'notnull' => false,
             ));
        $this->hasColumn('conference_id', 'bigint', null, array(
             'type' => 'bigint',
             'notnull' => false,
             ));
        $this->hasColumn('body', 'string', 65535, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 65535,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Parent', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Sender', array(
             'local' => 'sender_id',
             'foreign' => 'id'));

        $this->hasOne('Conference', array(
             'local' => 'conference_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'format' => 'Y-m-d H:i:s',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}