<?php

/**
 * BaseDefaultCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $user_id
 * @property bigint $conference_id
 * @property sfGuardUser $User
 * @property Conference $Conference
 * 
 * @method bigint          getUserId()        Returns the current record's "user_id" value
 * @method bigint          getConferenceId()  Returns the current record's "conference_id" value
 * @method sfGuardUser     getUser()          Returns the current record's "User" value
 * @method Conference      getConference()    Returns the current record's "Conference" value
 * @method DefaultCalendar setUserId()        Sets the current record's "user_id" value
 * @method DefaultCalendar setConferenceId()  Sets the current record's "conference_id" value
 * @method DefaultCalendar setUser()          Sets the current record's "User" value
 * @method DefaultCalendar setConference()    Sets the current record's "Conference" value
 * 
 * @package    platforms
 * @subpackage model
 * @author     Joerg Basedow <jbasedow@mindworks.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDefaultCalendar extends mwDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('default_calendar');
        $this->hasColumn('user_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('conference_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Conference', array(
             'local' => 'conference_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}