<?php

/**
 * BaseSeries
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $url
 * @property Doctrine_Collection $Contacts
 * @property Doctrine_Collection $Conferences
 * @property Doctrine_Collection $SeriesContact
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getUrl()           Returns the current record's "url" value
 * @method Doctrine_Collection getContacts()      Returns the current record's "Contacts" collection
 * @method Doctrine_Collection getConferences()   Returns the current record's "Conferences" collection
 * @method Doctrine_Collection getSeriesContact() Returns the current record's "SeriesContact" collection
 * @method Series              setName()          Sets the current record's "name" value
 * @method Series              setDescription()   Sets the current record's "description" value
 * @method Series              setUrl()           Sets the current record's "url" value
 * @method Series              setContacts()      Sets the current record's "Contacts" collection
 * @method Series              setConferences()   Sets the current record's "Conferences" collection
 * @method Series              setSeriesContact() Sets the current record's "SeriesContact" collection
 * 
 * @package    platforms
 * @subpackage model
 * @author     Joerg Basedow <jbasedow@mindworks.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeries extends mwDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('series');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 65535, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 65535,
             ));
        $this->hasColumn('url', 'string', 2048, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 2048,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Contacts', array(
             'refClass' => 'SeriesContact',
             'local' => 'series_id',
             'foreign' => 'user_id'));

        $this->hasMany('Conference as Conferences', array(
             'local' => 'id',
             'foreign' => 'series_id'));

        $this->hasMany('SeriesContact', array(
             'local' => 'id',
             'foreign' => 'series_id'));
    }
}