<?php

/**
 * BaseConferenceCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $conference_id
 * @property bigint $category_id
 * @property Conference $Conference
 * @property Category $Category
 * 
 * @method bigint             getConferenceId()  Returns the current record's "conference_id" value
 * @method bigint             getCategoryId()    Returns the current record's "category_id" value
 * @method Conference         getConference()    Returns the current record's "Conference" value
 * @method Category           getCategory()      Returns the current record's "Category" value
 * @method ConferenceCategory setConferenceId()  Sets the current record's "conference_id" value
 * @method ConferenceCategory setCategoryId()    Sets the current record's "category_id" value
 * @method ConferenceCategory setConference()    Sets the current record's "Conference" value
 * @method ConferenceCategory setCategory()      Sets the current record's "Category" value
 * 
 * @package    platforms
 * @subpackage model
 * @author     Joerg Basedow <jbasedow@mindworks.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConferenceCategory extends mwDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conference_category');
        $this->hasColumn('conference_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Conference', array(
             'local' => 'conference_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}