<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property string $fullname
 * @property string $town
 * @property string $country
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Contacts
 * @property Doctrine_Collection $ContactsOf
 * @property Doctrine_Collection $Notifications
 * @property Doctrine_Collection $DefaultCalendarItems
 * @property SearchIndex $Fulltext
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * @property Doctrine_Collection $Series
 * @property Doctrine_Collection $Conference
 * @property Doctrine_Collection $DefaultCalendar
 * @property Doctrine_Collection $ConferenceAttendee
 * @property Doctrine_Collection $SeriesContact
 * 
 * @method string                getFirstName()             Returns the current record's "first_name" value
 * @method string                getLastName()              Returns the current record's "last_name" value
 * @method string                getEmailAddress()          Returns the current record's "email_address" value
 * @method string                getUsername()              Returns the current record's "username" value
 * @method string                getAlgorithm()             Returns the current record's "algorithm" value
 * @method string                getSalt()                  Returns the current record's "salt" value
 * @method string                getPassword()              Returns the current record's "password" value
 * @method boolean               getIsActive()              Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()          Returns the current record's "is_super_admin" value
 * @method timestamp             getLastLogin()             Returns the current record's "last_login" value
 * @method string                getFullname()              Returns the current record's "fullname" value
 * @method string                getTown()                  Returns the current record's "town" value
 * @method string                getCountry()               Returns the current record's "country" value
 * @method Doctrine_Collection   getGroups()                Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getPermissions()           Returns the current record's "Permissions" collection
 * @method Doctrine_Collection   getContacts()              Returns the current record's "Contacts" collection
 * @method Doctrine_Collection   getContactsOf()            Returns the current record's "ContactsOf" collection
 * @method Doctrine_Collection   getNotifications()         Returns the current record's "Notifications" collection
 * @method Doctrine_Collection   getDefaultCalendarItems()  Returns the current record's "DefaultCalendarItems" collection
 * @method SearchIndex           getFulltext()              Returns the current record's "Fulltext" value
 * @method Doctrine_Collection   getSfGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getSfGuardUserGroup()      Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getRememberKeys()          Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getForgotPassword()        Returns the current record's "ForgotPassword" value
 * @method Doctrine_Collection   getSeries()                Returns the current record's "Series" collection
 * @method Doctrine_Collection   getConference()            Returns the current record's "Conference" collection
 * @method Doctrine_Collection   getDefaultCalendar()       Returns the current record's "DefaultCalendar" collection
 * @method Doctrine_Collection   getConferenceAttendee()    Returns the current record's "ConferenceAttendee" collection
 * @method Doctrine_Collection   getSeriesContact()         Returns the current record's "SeriesContact" collection
 * @method sfGuardUser           setFirstName()             Sets the current record's "first_name" value
 * @method sfGuardUser           setLastName()              Sets the current record's "last_name" value
 * @method sfGuardUser           setEmailAddress()          Sets the current record's "email_address" value
 * @method sfGuardUser           setUsername()              Sets the current record's "username" value
 * @method sfGuardUser           setAlgorithm()             Sets the current record's "algorithm" value
 * @method sfGuardUser           setSalt()                  Sets the current record's "salt" value
 * @method sfGuardUser           setPassword()              Sets the current record's "password" value
 * @method sfGuardUser           setIsActive()              Sets the current record's "is_active" value
 * @method sfGuardUser           setIsSuperAdmin()          Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setLastLogin()             Sets the current record's "last_login" value
 * @method sfGuardUser           setFullname()              Sets the current record's "fullname" value
 * @method sfGuardUser           setTown()                  Sets the current record's "town" value
 * @method sfGuardUser           setCountry()               Sets the current record's "country" value
 * @method sfGuardUser           setGroups()                Sets the current record's "Groups" collection
 * @method sfGuardUser           setPermissions()           Sets the current record's "Permissions" collection
 * @method sfGuardUser           setContacts()              Sets the current record's "Contacts" collection
 * @method sfGuardUser           setContactsOf()            Sets the current record's "ContactsOf" collection
 * @method sfGuardUser           setNotifications()         Sets the current record's "Notifications" collection
 * @method sfGuardUser           setDefaultCalendarItems()  Sets the current record's "DefaultCalendarItems" collection
 * @method sfGuardUser           setFulltext()              Sets the current record's "Fulltext" value
 * @method sfGuardUser           setSfGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setSfGuardUserGroup()      Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setRememberKeys()          Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setForgotPassword()        Sets the current record's "ForgotPassword" value
 * @method sfGuardUser           setSeries()                Sets the current record's "Series" collection
 * @method sfGuardUser           setConference()            Sets the current record's "Conference" collection
 * @method sfGuardUser           setDefaultCalendar()       Sets the current record's "DefaultCalendar" collection
 * @method sfGuardUser           setConferenceAttendee()    Sets the current record's "ConferenceAttendee" collection
 * @method sfGuardUser           setSeriesContact()         Sets the current record's "SeriesContact" collection
 * 
 * @package    platforms
 * @subpackage model
 * @author     Joerg Basedow <jbasedow@mindworks.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends mwDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('fullname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('town', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('Contact as Contacts', array(
             'local' => 'id',
             'foreign' => 'sender_id'));

        $this->hasMany('Contact as ContactsOf', array(
             'local' => 'id',
             'foreign' => 'receiver_id'));

        $this->hasMany('Notification as Notifications', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Conference as DefaultCalendarItems', array(
             'refClass' => 'DefaultCalendar',
             'local' => 'user_id',
             'foreign' => 'conference_id',
             'orderBy' => 'startdate'));

        $this->hasOne('SearchIndex as Fulltext', array(
             'local' => 'id',
             'foreign' => 'object_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Series', array(
             'refClass' => 'SeriesContact',
             'local' => 'user_id',
             'foreign' => 'series_id'));

        $this->hasMany('Conference', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('DefaultCalendar', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ConferenceAttendee', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('SeriesContact', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $geographical0 = new Doctrine_Template_Geographical(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($geographical0);
    }
}